# Generated by Django 2.2 on 2021-02-13 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20210212_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Phone Number.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Phone Number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
