# Generated by Django 2.2 on 2021-01-21 08:14

from django.db import migrations
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_order_dist_from_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=kitchen.models.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=kitchen.models.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_order',
            field=kitchen.models.DateTimeWithoutTZField(blank=True, null=True),
        ),
    ]
