# Generated by Django 2.2 on 2021-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20210213_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentOption',
            field=models.CharField(default='payadvance', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Packed', 'Packed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Picked', 'Picked'), ('Rejected', 'Rejected')], default='Waiting', max_length=50),
        ),
    ]
