# Generated by Django 2.2 on 2021-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20210209_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='resDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
