# Generated by Django 2.2 on 2021-02-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20210213_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentOption',
            field=models.CharField(max_length=20),
        ),
    ]
