# Generated by Django 2.2 on 2021-01-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20210121_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Placed', 'Placed'), ('Packed', 'Packed'), ('Preparing', 'Preparing'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Picked', 'Picked'), ('Rejected', 'Rejected')], default='Waiting', max_length=50),
        ),
    ]
