# Generated by Django 2.2 on 2021-02-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20210213_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='queries',
            name='message',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='queries',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='queries',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
