# Generated by Django 2.2 on 2021-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20210813_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_addr',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
