# Generated by Django 2.2 on 2021-02-09 13:26

from django.db import migrations
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20210209_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='reqDate',
            field=kitchen.models.DateTimeWithoutTZField(),
        ),
        migrations.AlterField(
            model_name='queries',
            name='resDate',
            field=kitchen.models.DateTimeWithoutTZField(null=True),
        ),
    ]
