# Generated by Django 2.2 on 2021-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20210209_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='reqDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='queries',
            name='resDate',
            field=models.DateTimeField(null=True),
        ),
    ]
