# Generated by Django 2.2 on 2021-01-30 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_kitchens_pureveg'),
        ('MainApp', '0006_auto_20210125_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='favouriteKitchens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Kitchens')),
            ],
        ),
    ]
