# Generated by Django 2.2 on 2021-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20210219_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couponId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
