# Generated by Django 2.2 on 2021-02-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0023_remove_userdiscountcoupons_validity'),
        ('MainApp', '0008_auto_20210219_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='couponId',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.UserDiscountCoupons'),
        ),
    ]
