# Generated by Django 2.2 on 2021-08-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_remove_order_paymentoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
