# Generated by Django 2.2 on 2021-02-09 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20210209_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 19, 26, 48, 852770)),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_order',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
