# Generated by Django 2.2 on 2021-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20210209_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_order',
            field=models.DateTimeField(null=True),
        ),
    ]
