# Generated by Django 2.2 on 2021-07-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_auto_20210620_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Placed', 'Placed'), ('Payment', 'Payment'), ('Preparing', 'Preparing'), ('Packed', 'Packed'), ('Cancelled', 'Cancelled'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Picked', 'Picked'), ('Rejected', 'Rejected')], default='Waiting', max_length=50),
        ),
    ]
