# Generated by Django 2.2 on 2021-01-07 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='deliveryTime',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
