# Generated by Django 2.2 on 2021-02-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='deliveryCharge',
            field=models.IntegerField(default=25),
        ),
    ]
