# Generated by Django 2.2 on 2021-07-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchens',
            old_name='visibilityRadius',
            new_name='deliveryRadius',
        ),
    ]
