# Generated by Django 2.2 on 2021-02-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchens_kitphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchens',
            name='kitPhone',
        ),
    ]
