# Generated by Django 2.2 on 2021-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchens_deliverytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='deliveryTime',
            field=models.TimeField(),
        ),
    ]
