# Generated by Django 2.2 on 2021-02-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchens_deliverycharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchens',
            name='registrationDate',
        ),
        migrations.RemoveField(
            model_name='kitchens',
            name='subscriptionExpiry',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='recharge_date',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='start_date',
        ),
    ]
