# Generated by Django 2.2 on 2021-08-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20210830_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemDesc',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
