# Generated by Django 2.2 on 2021-01-09 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20210107_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='registrationDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
