# Generated by Django 2.2 on 2021-02-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20210209_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='registrationDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='kitchens',
            name='subscriptionExpiry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='recharge_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
