# Generated by Django 2.2 on 2021-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20210109_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='registrationDate',
            field=models.DateTimeField(),
        ),
    ]
