# Generated by Django 2.2 on 2021-02-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_remove_kitchens_paytmno'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='kitPhone',
            field=models.CharField(default='9873025183', max_length=10, unique=True),
        ),
    ]
