# Generated by Django 2.2 on 2021-02-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_kitchens_kitphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchens',
            old_name='kitPhone',
            new_name='paytmNo',
        ),
    ]
