# Generated by Django 2.2 on 2021-01-21 08:18

from django.db import migrations
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20210110_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='registrationDate',
            field=kitchen.models.DateTimeWithoutTZField(),
        ),
    ]
