# Generated by Django 2.2 on 2021-01-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_auto_20210121_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='visibilityRadius',
            field=models.FloatField(default=2.0),
        ),
    ]
