# Generated by Django 2.2 on 2021-02-12 23:16

from django.db import migrations, models
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_auto_20210212_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='QRCode',
            field=models.ImageField(default='abcd', upload_to=kitchen.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='kitchens',
            name='paytmNo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
