# Generated by Django 2.2 on 2021-02-12 23:50

from django.db import migrations, models
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20210212_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='QRCode',
            field=models.ImageField(upload_to=kitchen.models.get_upload_path),
        ),
    ]
