# Generated by Django 2.2 on 2021-01-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_kitchens_visibilityradius'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='pureVeg',
            field=models.BooleanField(default=False),
        ),
    ]
