# Generated by Django 2.2 on 2021-01-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_kitchens_pureveg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchens',
            name='deliveryTime',
        ),
    ]
