# Generated by Django 2.2 on 2021-01-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_remove_kitchens_deliverytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='deliveryTime',
            field=models.IntegerField(default=45),
        ),
    ]
