# Generated by Django 2.2 on 2021-02-02 05:41

import datetime
from django.db import migrations
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_kitchens_deliverytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='subscriptionExpiry',
            field=kitchen.models.DateTimeWithoutTZField(default=datetime.datetime(2021, 2, 2, 11, 11, 23, 360727)),
        ),
    ]
