# Generated by Django 2.2 on 2021-02-13 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_auto_20210213_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchens',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='kitchens',
            name='paytmNo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Phone Number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
