# Generated by Django 2.2 on 2021-02-13 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0005_auto_20210213_2006'),
        ('kitchen', '0012_auto_20210213_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsAndRefunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Under Process', 'Under Process'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Under Process', max_length=20)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Kitchens')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
