# Generated by Django 2.2 on 2021-02-02 05:59

from django.db import migrations, models
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0012_kitchens_subscriptionexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='subscriptionExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kitchens',
            name='subscriptionExpiry',
            field=kitchen.models.DateTimeWithoutTZField(),
        ),
    ]
