# Generated by Django 2.2 on 2021-02-03 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0013_auto_20210202_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=30)),
                ('recharge_date', kitchen.models.DateTimeWithoutTZField()),
                ('amount', models.IntegerField()),
                ('start_date', kitchen.models.DateTimeWithoutTZField()),
                ('end_date', kitchen.models.DateTimeWithoutTZField()),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Kitchens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
