# Generated by Django 2.2 on 2021-02-13 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0013_complaintsandrefunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsandrefunds',
            name='paytmNo',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter a Valid Phone Number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
