# Generated by Django 2.2 on 2021-02-14 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0014_complaintsandrefunds_paytmno'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsandrefunds',
            name='closing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='complaintsandrefunds',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 13, 38, 46, 534905)),
        ),
        migrations.AlterField(
            model_name='complaintsandrefunds',
            name='status',
            field=models.CharField(choices=[('Under Process', 'Under Process'), ('Closed', 'Closed')], default='Under Process', max_length=20),
        ),
    ]
