# Generated by Django 2.2 on 2021-02-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0015_planlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.PlanList'),
        ),
    ]
