# Generated by Django 2.2 on 2021-02-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0016_auto_20210214_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsandrefunds',
            name='subject',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
