# Generated by Django 2.2 on 2021-02-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0017_complaintsandrefunds_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsandrefunds',
            name='status',
            field=models.CharField(choices=[('Under Process', 'Under Process'), ('Closed', 'Closed')], default='Under Process', max_length=50),
        ),
    ]
