# Generated by Django 2.2 on 2021-02-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0018_auto_20210214_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsandrefunds',
            name='status',
            field=models.CharField(choices=[('Under Process', 'Under Process'), ('Closed', 'Closed')], default='Under Process', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintsandrefunds',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
