# Generated by Django 2.2 on 2021-02-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0019_auto_20210214_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsandrefunds',
            name='issue',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
