# Generated by Django 2.2 on 2021-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0020_auto_20210214_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsandrefunds',
            name='paytmNo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='kitchens',
            name='paytmNo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
