# Generated by Django 2.2 on 2021-02-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0022_userdiscountcoupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiscountcoupons',
            name='validity',
        ),
    ]
