# Generated by Django 2.2 on 2021-02-20 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0023_remove_userdiscountcoupons_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscountcoupons',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
