# Generated by Django 2.2 on 2021-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0024_auto_20210220_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscountcoupons',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
