# Generated by Django 2.2 on 2021-04-27 11:19

from django.db import migrations, models
import kitchen.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0025_auto_20210220_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='chefDp',
            field=models.ImageField(blank=True, upload_to=kitchen.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='kitchens',
            name='youTubeLink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kitchens',
            name='youTubeReview',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
